name: Deploy to Production

on:
    push:
        branches:
            - master
    workflow_dispatch:
        inputs:
            environment:
                description: 'Deployment environment'
                required: true
                default: 'production'
                type: choice
                options:
                    - production
                    - staging

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello, World!"
    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Test Step
              run: echo "This is a test step after the build job."
    docker:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Docker Build and Push
              run: echo "Building and pushing Docker image..."
            - name: Deploy to ${{ github.event.inputs.environment }}
              run: |
                echo "Deploying to ${{ github.event.inputs.environment }} environment..."
                if [ "${{ github.event.inputs.environment }}" == "production" ]; then
                    echo "Deploying to production server..."
                else
                    echo "Deploying to staging server..."
                fi
    deploy:
        runs-on: ubuntu-latest
        needs: docker
        steps:
            - name: Deploy Application
              run: echo "Deploying application to the server..."
            - name: Notify Deployment Success
              run: echo "Deployment to ${{ github.event.inputs.environment }} successful!"